## إعدادات تحليل الكود (Lint) لمشروع Flutter
# invoked from the command line by running `flutter analyze`.
include: package:flutter_lints/flutter.yaml


analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: warning
    dead_code: warning
    unused_import: warning
    unnecessary_null_checks: warning
    argument_type_not_assignable: warning
    missing_required_param: error
    missing_return: error
    return_of_invalid_type_from_closure: ignore

linter:
  #    # قواعد عامة
  rules:
    always_declare_return_types: true
    annotate_overrides: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    require_trailing_commas: true

    #    # الأداء
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    prefer_single_quotes: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    avoid_init_to_null: true

    #    # التنظيم والهيكل
    directives_ordering: true
    sort_child_properties_last: true
    unnecessary_this: true
    use_key_in_widget_constructors: true

    #    # لمشروعات كبيرة
    unnecessary_lambdas: true
    avoid_positional_boolean_parameters: true

    #    # قواعد Flutter
    prefer_const_constructors_in_immutables: true
    avoid_setters_without_getters: true
